api:
  github:
    user:
      me: https://api.github.com/user
    project:
      organization: https://api.github.com/orgs/{organization}/projectsV2
      individual: https://api.github.com/users/{username}/projects
    repository:
      list: https://api.github.com/user/{username}/repos
      issue:
        list: https://api.github.com/repos/{owner}/{repo}/issues
        create: https://api.github.com/repos/{owner}/{repo}/issues
        detail: https://api.github.com/repos/{owner}/{repo}/issues/{issueNumber}
        update: https://api.github.com/repos/{owner}/{repo}/issues/{issueNumber}
  gitlab:
    user:
      profile: https://gitlab.com/api/v4/user
      project:
        list: https://gitlab.com/api/v4/users/{userId}/projects
    organization:
      project:
        list: https://gitlab.com/api/v4/projects
    project:
      issue:
        list: https://gitlab.com/api/v4/projects/{projectId}/issues
        create: https://gitlab.com/api/v4/projects/{projectId}/issues
        update: https://gitlab.com/api/v4/projects/{projectId}/issues/{issueId}
        detail: https://gitlab.com/api/v4/projects/{projectId}/issues/{issueId}
        delete: https://gitlab.com/api/v4/projects/{projectId}/issues/{issueId}
    issue:
      list: https://gitlab.com/api/v4/issues
      detail: https://gitlab.com/api/v4/issues/{issueId}
